/**
 * Backfill the local agents table with real Circle wallet addresses + ERC-8004 token IDs.
 *
 * Reads:  WALLET_ID_* env (Circle wallet IDs) + ERC8004_TOKEN_ID_* env (NFT IDs).
 * Calls:  getAgentAddress() per agent (Circle REST API — read-only, no DB writes).
 * Emits:  6 UPDATE statements to stdout, ready to pipe into psql.
 *
 * Usage:
 *   npx ts-node scripts/backfill-agent-addresses.ts > /tmp/backfill.sql
 *   docker exec -i supabase_db_SwarmPay psql -U postgres -d postgres < /tmp/backfill.sql
 */
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

import { getAgentAddress } from '../src/lib/circleWallets'

const AGENTS = [
  'crypto-scout-x',
  'research-alpha',
  'data-miner-pro',
  'parser-x',
  'analysis-node',
  'compute-grid-4',
] as const

function tokenIdEnvKey(agentId: string): string {
  return `ERC8004_TOKEN_ID_${agentId.toUpperCase().replace(/-/g, '_')}`
}

async function main() {
  console.error('-- Fetching wallet addresses from Circle API…')
  const lines: string[] = []

  for (const agentId of AGENTS) {
    const tokenId = process.env[tokenIdEnvKey(agentId)] ?? null
    let address: string
    try {
      address = await getAgentAddress(agentId)
    } catch (e) {
      console.error(`-- ${agentId}: getAgentAddress threw — ${e instanceof Error ? e.message : e}`)
      address = ''
    }

    if (!address) {
      console.error(`-- ${agentId}: no address resolved (skipping UPDATE)`)
      continue
    }

    const tokenIdSql = tokenId ? `'${tokenId}'` : 'NULL'
    lines.push(
      `UPDATE agents SET wallet_address = '${address}', erc8004_token_id = ${tokenIdSql} WHERE id = '${agentId}';`
    )
    console.error(`-- ${agentId} → ${address} (tokenId ${tokenId ?? '—'})`)
  }

  // SQL goes to stdout, log noise goes to stderr — clean to pipe.
  console.log('-- Backfill generated by scripts/backfill-agent-addresses.ts')
  console.log('BEGIN;')
  for (const line of lines) console.log(line)
  console.log('COMMIT;')
  console.log('SELECT id, wallet_address, erc8004_token_id FROM agents ORDER BY id;')
}

main().catch(e => {
  console.error('FATAL:', e)
  process.exit(1)
})
